Form tools qa
RodCastDev/cypress-training pull request #9
Opened 2023-10-08 14:53 UTC by RodCastDev

2023-10-10 15:34 UTC, RodCastDev commented
![image](https://github.com/RodCastDev/cypress-training/assets/101688534/558d9384-261a-4c79-bfcf-d1b262e14c81)

2023-10-11 00:12 UTC, DanielCalleCO requested changes

2023-10-11 00:12 UTC, DanielCalleCO commented on cypress.config.ts
> +    // baseUrl: "https://www.demoblaze.com",
borra esto

2023-10-11 00:12 UTC, DanielCalleCO commented on .github/workflows/main.yml
> +        run: npx cypress run --browser chrome --headed --config viewportWidth=1920,viewportHeight=1080
regresa al original

2023-10-11 00:12 UTC, DanielCalleCO commented on cypress.config.ts
> +    defaultCommandTimeout: 50000,
20000

2023-10-11 00:12 UTC, DanielCalleCO commented on cypress.config.ts
> +  viewportHeight: 1080,
borrar

2023-10-11 00:53 UTC, DanielCalleCO approved these changes

2023-10-11 13:36 UTC, merged